"""Initial migration

Revision ID: 11b4b916a0d6
Revises: 
Create Date: 2025-11-17 09:47:12.074876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b4b916a0d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_insights', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))
        batch_op.drop_column('result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('avatar')
        batch_op.drop_column('weekly_insights')

    # ### end Alembic commands ###
