"""Add intake form fields

Revision ID: eb03980ec9ad
Revises: e9836623f9c7
Create Date: 2025-11-26 13:12:11.374810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb03980ec9ad'
down_revision = 'e9836623f9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('service_therapy', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('service_psychiatry', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('service_substance', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('service_not_sure', sa.Boolean(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('service_not_sure')
        batch_op.drop_column('service_substance')
        batch_op.drop_column('service_psychiatry')
        batch_op.drop_column('service_therapy')
        batch_op.drop_column('dob')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
